### ISSUE TITLE
Consider using AsRef for public APIs

### ISSUE THREAD

**Issue by Stebalien** [GildedHonour/atarashii_imap#2]
When accepting references to stringy types, it can be useful to accept a generic `S: AsRef<T>` where `T` is the target stringy type (e.g., `str`). For example:

``` rust
fn my_fn<S: AsRef<str>>(my_name: S) {
    let my_name: &str = my_name.as_ref();
    println!("{}", my_name);
}
```

Can be called with owned `String`s, `&str`s, or any other custom string-like type that implements `AsRef<str>`.

**Comment by GildedHonour** [comment]
Why would it be useful?

**Comment by Stebalien** [comment]
It means that the function can be called with anything string like: `Box<str>`, `&str`, `String`, `&String`, `&MySpecialString` (as long as `MySpecialString` implements the `AsRef<str>` conversion trait).

**Comment by Stebalien** [comment]
It means that the function can be called with anything string like: `Box<str>`, `&str`, `String`, `&String`, `&MySpecialString` (as long as `MySpecialString` implements the `AsRef<str>` conversion trait).

**Comment by Stebalien** [comment]
Actually, ignore this. `AsRef` is often used for things like `Path` (so you can pass an `&str` and have it automatically converted to a `&Path`) but it's almost never used for strings. I don't really know what I was thinking.

**Comment by GildedHonour** [comment]
No problem :)

Sent from my ASUS

-------- オリジナルのメッセージ --------
送信元:Steven Allen notifications@github.com
送信済み:Sun, 03 Jul 2016 00:56:16 +0800
送信先:GildedHonour/atarashii_imap atarashii_imap@noreply.github.com
Cc:Alex Maslakov me@gildedhonour.com,Comment comment@noreply.github.com
件名:Re: [GildedHonour/atarashii_imap] Consider using AsRef for public APIs (#2)
